include:
  - file: /r4.3/gitlab-base.yml
    project: QubesOS/qubes-continuous-integration
  - file: /r4.3/gitlab-host.yml
    project: QubesOS/qubes-continuous-integration
  - file: /r4.3/gitlab-vm.yml
    project: QubesOS/qubes-continuous-integration

.qrexec_checks:
  stage: checks
  tags:
    - vm
  before_script: &before-script
    - "PATH=$PATH:$HOME/.local/bin"
    - sudo dnf install -y python3-pip python3-gobject gtk3 python3-pytest
        python3-coverage python3-devel pam-devel pandoc gcc git make findutils clang
        xorg-x11-server-Xvfb python3-pytest-asyncio python3-inotify sequoia-sqv
    - git config --global --add safe.directory "${CI_PROJECT_DIR}"
    - git clone https://github.com/QubesOS/qubes-core-vchan-socket ~/qubes-core-vchan-socket
    - make -C ~/qubes-core-vchan-socket all
    - sudo make -C ~/qubes-core-vchan-socket install LIBDIR=/usr/lib64
    - pip3 install --user --quiet -r ci/requirements.txt

checks:pylint:
  extends: .qrexec_checks
  script:
    - python3 -m pylint qrexec

checks:tests:
  extends: .qrexec_checks
  variables:
    PYTEST_ADDOPTS: "--color=yes"
  script:
    - xvfb-run ./run-tests
  after_script:
    - (cd libqrexec; gcov *.c)
    - (cd daemon; gcov *.c)
    - (cd agent; gcov *.c)
    - ci/codecov-wrapper --gcov

checks:fuzz:
  extends: .qrexec_checks
  script:
   - make -C fuzz test
