version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
  - gobject-introspection
  - libgirepository1.0-dev

sphinx:
  configuration: doc/conf.py

python:
  install:
  - requirements: ci/requirements.txt
  - requirements: ci/doc-requirements.txt
