#!/bin/bash -x

DIR=qubesrpc_parse_fuzzer_seed_corpus

rm -rf $DIR
mkdir -p $DIR

echo -ne 'user:ls -la' >$DIR/cmd
echo -ne 'user:nogui:ls -la' >$DIR/cmd_nogui
echo -ne 'user:QUBESRPC qubes.Service domX' >$DIR/rpc
echo -ne 'user:QUBESRPC qubes.Service+arg domX' >$DIR/rpc_arg

DIR=qrexec_remote_fuzzer_seed_corpus

rm -rf $DIR
mkdir -p $DIR

echo -ne '\x90\x01\0\0\x0A\0\0\0stdin data' >$DIR/stdin_data
echo -ne '\x91\x01\0\0\x0B\0\0\0stdout data' >$DIR/stdout_data
echo -ne '\x92\x01\0\0\x0B\0\0\0stderr data' >$DIR/stderr_data
echo -ne '\x93\x01\0\0\x04\0\0\0\xAA\0\0\0' >$DIR/exit_code

DIR=qrexec_daemon_fuzzer_seed_corpus

rm -rf $DIR
mkdir -p $DIR

echo -ne '\x03\x11\x02\0\0\x08\0\0\0\0\0\0\0\0' >$DIR/connection_terminate
echo -ne '\x02\x10\x02\0\0\x80\0\0\0qrexec.Service+arg\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0target\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\01234\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0' >$DIR/trigger_service2
echo -ne '\x03\x12\x02\0\0\x73\0\0\0target\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\01234\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0qrexec.Service+arg\0' >$DIR/trigger_service3
